### ISSUE TITLE
Bug: ERP zwiwn missing

### ISSUE THREAD

**Issue by xenedium** [Yahya-rabii/TP3#1]
Where is T zwiwn ERP Model?

**Comment by Yahya-rabii** [comment]
tarik zwiwn is missing

**Comment by Yahya-rabii** [comment]
![Capture](https://user-images.githubusercontent.com/92509001/226307616-96d9803d-cb2b-40ac-906e-acf0935acf3b.PNG)

**Comment by Yahya-rabii** [comment]
tarik zwiwn was added

**Comment by Yahya-rabii** [comment]
@xenedium @MatrixcsYounes
